version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: ong_pets_postgres
    restart: always
    environment:
      POSTGRES_DB: ong_pets_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local