version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: ong_pets_postgres
    restart: always
    environment:
      POSTGRES_DB: ong_pets_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ong_pets_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ong_pets_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Sobrescreve o host do banco para apontar para o container postgres-db
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/ong_pets_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha123
    depends_on:
      postgres-db:
        condition: service_healthy   # Espera o banco estar 100% operacional antes de subir o Spring

volumes:
  pgdata:
    driver: local