-- =============================================================================
-- MIGRATION V2: Carga Inicial de Dados Fictícios (Seed)
-- Locais: Natal e Parnamirim - RN
-- Quantidades: 30 Pessoas (Adotantes/Tutores) e 100 Pets (Adotados/Disponíveis)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. INSERÇÃO DE 30 ADOTANTES / TUTORES (IDs 1 a 30)
-- -----------------------------------------------------------------------------
INSERT INTO adotantes (nome, cpf, telefone, email, logradouro, numero, cidade) VALUES
-- Natal - RN
('Carlos Eduardo Silva', '10120230301', '(84) 98811-2233', 'carlos.silva@email.com', 'Av. Engenheiro Roberto Freire', '1420', 'Natal'),
('Mariana Lima Souza', '10120230302', '(84) 98722-3344', 'mariana.lima@email.com', 'Rua Jaguarari', '850', 'Natal'),
('Rafael Medeiros Costa', '10120230303', '(84) 99933-4455', 'rafael.costa@email.com', 'Av. Hermes da Fonseca', '512', 'Natal'),
('Juliana Dantas Fonseca', '10120230304', '(84) 98144-5566', 'juliana.dantas@email.com', 'Rua Afonso Pena', '204', 'Natal'),
('Lucas Gabriel Xavier', '10120230305', '(84) 99655-6677', 'lucas.xavier@email.com', 'Av. Prudente de Morais', '3100', 'Natal'),
('Beatriz Rocha Aguiar', '10120230306', '(84) 98866-7788', 'beatriz.rocha@email.com', 'Rua Apodi', '118', 'Natal'),
('Fernando Henrique Castro', '10120230307', '(84) 98777-8899', 'fernando.castro@email.com', 'Av. Senador Salgado Filho', '2250', 'Natal'),
('Camila Fernandes Melo', '10120230308', '(84) 99188-9900', 'camila.melo@email.com', 'Rua Sao Jose', '432', 'Natal'),
('Thiago Bezerra Araujo', '10120230309', '(84) 98899-0011', 'thiago.araujo@email.com', 'Av. Bernardo Vieira', '1800', 'Natal'),
('Amanda Vitoria Martins', '10120230310', '(84) 99400-1122', 'amanda.martins@email.com', 'Rua Trairi', '605', 'Natal'),
('Rodrigo Alves Pinheiro', '10120230311', '(84) 98711-2233', 'rodrigo.pinheiro@email.com', 'Rua Mossoro', '320', 'Natal'),
('Patricia Siqueira Cavalcanti', '10120230312', '(84) 99822-3344', 'patricia.cavalcanti@email.com', 'Av. Amintas Barros', '2700', 'Natal'),
('Gabriel Vinicius Ramos', '10120230313', '(84) 98133-4455', 'gabriel.ramos@email.com', 'Rua Potengi', '412', 'Natal'),
('Larissa Montenegro Paiva', '10120230314', '(84) 99644-5566', 'larissa.paiva@email.com', 'Av. Afonso Pena', '980', 'Natal'),
('Diego Macedo Farias', '10120230315', '(84) 98855-6677', 'diego.farias@email.com', 'Rua Princesa Isabel', '150', 'Natal'),

-- Parnamirim - RN
('Vanessa Cristina Nobre', '10120230316', '(84) 98766-7788', 'vanessa.nobre@email.com', 'Av. Maria Lacerda Montenegro', '1200', 'Parnamirim'),
('Bruno Felipe Duarte', '10120230317', '(84) 99977-8899', 'bruno.duarte@email.com', 'Rua Abel Cabral', '540', 'Parnamirim'),
('Leticia Maria Santiago', '10120230318', '(84) 98188-9900', 'leticia.santiago@email.com', 'Av. Olavo Lacerda Montenegro', '310', 'Parnamirim'),
('Gustavo Henrique Teixeira', '10120230319', '(84) 99699-0011', 'gustavo.teixeira@email.com', 'Rua Candido Martins', '88', 'Parnamirim'),
('Isabela Regina Tavares', '10120230320', '(84) 98800-1122', 'isabela.tavares@email.com', 'Av. Tenente General Telles Ribeiro', '205', 'Parnamirim'),
('Marcelo Augusto Brito', '10120230321', '(84) 98711-3344', 'marcelo.brito@email.com', 'Rua Subtenente Francisco Hierro', '42', 'Parnamirim'),
('Natalia Queiroz Freitas', '10120230322', '(84) 99922-4455', 'natalia.freitas@email.com', 'Av. Sao Miguel dos Cariris', '150', 'Parnamirim'),
('Vinicius Andrade Barros', '10120230323', '(84) 98133-5566', 'vinicius.barros@email.com', 'Rua Projetada A', '12', 'Parnamirim'),
('Deborah Suely Guimaraes', '10120230324', '(84) 99644-6677', 'deborah.guimaraes@email.com', 'Av. Prefeito Gabriel Deocleciano', '890', 'Parnamirim'),
('Leonardo Cesar Fontes', '10120230325', '(84) 98855-7788', 'leonardo.fontes@email.com', 'Rua Pedro Bezerra Filho', '302', 'Parnamirim'),
('Priscila Helena Nogueira', '10120230326', '(84) 98766-8899', 'priscila.nogueira@email.com', 'Av. Brigadeiro Everaldo Breves', '620', 'Parnamirim'),
('Andre Luis Vasconcelos', '10120230327', '(84) 99977-9900', 'andre.vasconcelos@email.com', 'Rua Eucaliptos', '104', 'Parnamirim'),
('Jessica Danielle Miranda', '10120230328', '(84) 98188-0011', 'jessica.miranda@email.com', 'Av. Santos Dumont', '450', 'Parnamirim'),
('Daniel Victor Holanda', '10120230329', '(84) 99699-1122', 'daniel.holanda@email.com', 'Rua Francisco Pignataro', '75', 'Parnamirim'),
('Sofia Emanuelle Borges', '10120230330', '(84) 98800-2233', 'sofia.borges@email.com', 'Av. Castor Vieira', '915', 'Parnamirim');


-- -----------------------------------------------------------------------------
-- 2. INSERÇÃO DE 100 PETS
-- ~45 Pets com Tutores (id_tutor de 1 a 20)
-- ~55 Pets Disponíveis para Adoção (id_tutor IS NULL)
-- -----------------------------------------------------------------------------
INSERT INTO pets (nome, tipo, sexo, raca, idade, peso, id_tutor, logradouro, numero, cidade) VALUES
-- Pets Adotados (Tutores 1 a 20)
('Thor', 'CACHORRO', 'MACHO', 'Golden Retriever', '3 anos', '30.5 kg', 1, 'Av. Engenheiro Roberto Freire', '1420', 'Natal'),
('Luna', 'GATO', 'FEMEA', 'Siames', '2 anos', '4.2 kg', 1, 'Av. Engenheiro Roberto Freire', '1420', 'Natal'),
('Mel', 'CACHORRO', 'FEMEA', 'Vira-Lata (SRD)', '1 ano', '12.0 kg', 2, 'Rua Jaguarari', '850', 'Natal'),
('Bob', 'CACHORRO', 'MACHO', 'Poodle', '5 anos', '7.8 kg', 3, 'Av. Hermes da Fonseca', '512', 'Natal'),
('Mimi', 'GATO', 'FEMEA', 'Persa', '4 anos', '3.9 kg', 3, 'Av. Hermes da Fonseca', '512', 'Natal'),
('Simba', 'GATO', 'MACHO', 'Angora', '2 anos', '5.1 kg', 4, 'Rua Afonso Pena', '204', 'Natal'),
('Buldogue', 'CACHORRO', 'MACHO', 'Bulldog Frances', '2 anos', '11.5 kg', 5, 'Av. Prudente de Morais', '3100', 'Natal'),
('Pipoca', 'CACHORRO', 'FEMEA', 'Shih Tzu', '3 anos', '5.5 kg', 6, 'Rua Apodi', '118', 'Natal'),
('Fred', 'CACHORRO', 'MACHO', 'Beagle', '4 anos', '14.2 kg', 7, 'Av. Senador Salgado Filho', '2250', 'Natal'),
('Nina', 'GATO', 'FEMEA', 'Vira-Lata (SRD)', '1 ano', '3.1 kg', 8, 'Rua Sao Jose', '432', 'Natal'),
('Max', 'CACHORRO', 'MACHO', 'Rottweiler', '6 anos', '42.0 kg', 9, 'Av. Bernardo Vieira', '1800', 'Natal'),
('Amora', 'CACHORRO', 'FEMEA', 'Lhasa Apso', '2 anos', '6.0 kg', 10, 'Rua Trairi', '605', 'Natal'),
('Chico', 'GATO', 'MACHO', 'Maine Coon', '3 anos', '8.5 kg', 11, 'Rua Mossoro', '320', 'Natal'),
('Belinha', 'CACHORRO', 'FEMEA', 'Yorkshire', '5 anos', '3.8 kg', 12, 'Av. Amintas Barros', '2700', 'Natal'),
('Zeus', 'CACHORRO', 'MACHO', 'Pastor Alemao', '4 anos', '35.0 kg', 13, 'Rua Potengi', '412', 'Natal'),
('Pandora', 'GATO', 'FEMEA', 'Sphynx', '2 anos', '3.5 kg', 14, 'Av. Afonso Pena', '980', 'Natal'),
('Tobias', 'CACHORRO', 'MACHO', 'Dachshund', '3 anos', '8.0 kg', 15, 'Rua Princesa Isabel', '150', 'Natal'),
('Floquinho', 'GATO', 'MACHO', 'Persa', '1 ano', '3.7 kg', 16, 'Av. Maria Lacerda Montenegro', '1200', 'Parnamirim'),
('Sombra', 'GATO', 'MACHO', 'Vira-Lata (SRD)', '2 anos', '4.5 kg', 16, 'Av. Maria Lacerda Montenegro', '1200', 'Parnamirim'),
('Cacau', 'CACHORRO', 'FEMEA', 'Labrador', '3 anos', '28.0 kg', 17, 'Rua Abel Cabral', '540', 'Parnamirim'),
('Marley', 'CACHORRO', 'MACHO', 'Golden Retriever', '5 anos', '32.0 kg', 18, 'Av. Olavo Lacerda Montenegro', '310', 'Parnamirim'),
('Frida', 'GATO', 'FEMEA', 'Siames', '2 anos', '4.0 kg', 19, 'Rua Candido Martins', '88', 'Parnamirim'),
('Ares', 'CACHORRO', 'MACHO', 'Doberman', '3 anos', '38.0 kg', 20, 'Av. Tenente General Telles Ribeiro', '205', 'Parnamirim'),

-- Pets Disponíveis para Adoção (id_tutor IS NULL) - ONG Localizada em Natal e Parnamirim
('Akira', 'CACHORRO', 'FEMEA', 'Akita', '2 anos', '24.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Apolo', 'CACHORRO', 'MACHO', 'Pinscher', '1 ano', '3.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Bartho', 'CACHORRO', 'MACHO', 'Vira-Lata (SRD)', '6 meses', '6.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Bela', 'GATO', 'FEMEA', 'Vira-Lata (SRD)', '8 meses', '2.8 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Bento', 'GATO', 'MACHO', 'Vira-Lata (SRD)', '1 ano', '4.1 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Billy', 'CACHORRO', 'MACHO', 'Maltes', '2 anos', '4.5 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Bingo', 'CACHORRO', 'MACHO', 'Vira-Lata (SRD)', '3 anos', '15.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Biscoito', 'GATO', 'MACHO', 'Angora', '5 meses', '2.1 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Bolinha', 'CACHORRO', 'FEMEA', 'Pug', '1 ano', '7.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Brutus', 'CACHORRO', 'MACHO', 'Boxer', '4 anos', '29.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Bud', 'CACHORRO', 'MACHO', 'Basset Hound', '2 anos', '18.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Catarina', 'GATO', 'FEMEA', 'Persa', '3 anos', '4.0 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Champagne', 'GATO', 'FEMEA', 'Siames', '1 ano', '3.5 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Chester', 'CACHORRO', 'MACHO', 'Chihuahua', '2 anos', '2.5 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Cloe', 'CACHORRO', 'FEMEA', 'Cocker Spaniel', '3 anos', '12.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Cookie', 'GATO', 'MACHO', 'Vira-Lata (SRD)', '4 meses', '1.8 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Costelinha', 'CACHORRO', 'MACHO', 'Vira-Lata (SRD)', '2 anos', '10.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Dali', 'GATO', 'MACHO', 'Ragdoll', '1 ano', '5.0 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Duke', 'CACHORRO', 'MACHO', 'Great Dane', '3 anos', '55.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Fiona', 'CACHORRO', 'FEMEA', 'Shar Pei', '2 anos', '19.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Garfield', 'GATO', 'MACHO', 'Vira-Lata (SRD)', '4 anos', '6.2 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Gatão', 'GATO', 'MACHO', 'Maine Coon', '2 anos', '7.9 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Goliad', 'CACHORRO', 'MACHO', 'Sao Bernardo', '5 anos', '65.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Guto', 'GATO', 'MACHO', 'Vira-Lata (SRD)', '7 meses', '2.9 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Hulk', 'CACHORRO', 'MACHO', 'Pitbull', '3 anos', '31.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Ian', 'CACHORRO', 'MACHO', 'Border Collie', '1 ano', '16.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Iron', 'CACHORRO', 'MACHO', 'Husky Siberiano', '2 anos', '23.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Jade', 'GATO', 'FEMEA', 'Vira-Lata (SRD)', '1 ano', '3.3 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Jasmim', 'GATO', 'FEMEA', 'Angora', '2 anos', '3.8 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Kira', 'CACHORRO', 'FEMEA', 'Pastor Belga', '3 anos', '26.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Lady', 'CACHORRO', 'FEMEA', 'Cavalier', '1 ano', '6.5 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Loki', 'GATO', 'MACHO', 'Vira-Lata (SRD)', '8 meses', '3.0 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Luigi', 'GATO', 'MACHO', 'Siames', '3 anos', '4.4 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Luffy', 'CACHORRO', 'MACHO', 'Vira-Lata (SRD)', '5 meses', '5.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Madona', 'CACHORRO', 'FEMEA', 'Poodle', '4 anos', '6.8 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Mica', 'GATO', 'FEMEA', 'Vira-Lata (SRD)', '2 anos', '3.6 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Milo', 'CACHORRO', 'MACHO', 'Jack Russell', '1 ano', '7.2 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Nala', 'GATO', 'FEMEA', 'Vira-Lata (SRD)', '1 ano', '3.2 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Nero', 'CACHORRO', 'MACHO', 'Cane Corso', '2 anos', '45.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Oliver', 'GATO', 'MACHO', 'Persa', '2 anos', '4.1 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Orion', 'CACHORRO', 'MACHO', 'Dalmata', '3 anos', '22.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Oscar', 'GATO', 'MACHO', 'Vira-Lata (SRD)', '4 anos', '5.0 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Panda', 'CACHORRO', 'MACHO', 'Pastor Australiano', '2 anos', '20.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Pantera', 'GATO', 'FEMEA', 'Vira-Lata (SRD)', '3 anos', '4.0 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Pingo', 'CACHORRO', 'MACHO', 'Chihuahua', '1 ano', '2.2 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Pluto', 'CACHORRO', 'MACHO', 'Bloodhound', '4 anos', '33.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Pingo de Ouro', 'GATO', 'MACHO', 'Vira-Lata (SRD)', '6 meses', '2.3 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Princesa', 'CACHORRO', 'FEMEA', 'Maltes', '3 anos', '3.9 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Rabito', 'CACHORRO', 'MACHO', 'Vira-Lata (SRD)', '2 anos', '11.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Ramses', 'GATO', 'MACHO', 'Sphynx', '1 ano', '3.4 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Rayan', 'CACHORRO', 'MACHO', 'Pastor Suico', '3 anos', '30.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Rex', 'CACHORRO', 'MACHO', 'Vira-Lata (SRD)', '5 anos', '14.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Romeo', 'GATO', 'MACHO', 'Siames', '2 anos', '4.3 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Ringo', 'CACHORRO', 'MACHO', 'Schnauzer', '2 anos', '8.5 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Sasha', 'CACHORRO', 'FEMEA', 'Samoieda', '3 anos', '21.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Salem', 'GATO', 'MACHO', 'Vira-Lata (SRD)', '1 ano', '3.8 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Sammy', 'CACHORRO', 'MACHO', 'Golden Retriever', '1 ano', '27.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Scooby', 'CACHORRO', 'MACHO', 'Great Dane', '2 anos', '48.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Serena', 'GATO', 'FEMEA', 'Persa', '4 anos', '3.9 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Simbal', 'CACHORRO', 'MACHO', 'Chow Chow', '3 anos', '25.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Spike', 'CACHORRO', 'MACHO', 'Bull Terrier', '2 anos', '24.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Taz', 'CACHORRO', 'MACHO', 'Vira-Lata (SRD)', '8 meses', '9.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Teddy', 'CACHORRO', 'MACHO', 'Poodle', '3 anos', '6.2 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Tigresa', 'GATO', 'FEMEA', 'Vira-Lata (SRD)', '2 anos', '4.0 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Titi', 'GATO', 'FEMEA', 'Vira-Lata (SRD)', '5 meses', '1.9 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Toby', 'CACHORRO', 'MACHO', 'Beagle', '2 anos', '13.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Tom', 'GATO', 'MACHO', 'Vira-Lata (SRD)', '3 anos', '4.8 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Tornado', 'CACHORRO', 'MACHO', 'Border Collie', '4 anos', '19.5 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Tuca', 'GATO', 'FEMEA', 'Angora', '1 ano', '3.2 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Tyson', 'CACHORRO', 'MACHO', 'American Bully', '2 anos', '32.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Ulysses', 'CACHORRO', 'MACHO', 'Basset Hound', '5 anos', '17.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Vicky', 'CACHORRO', 'FEMEA', 'Shih Tzu', '2 anos', '5.2 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Whisky', 'CACHORRO', 'MACHO', 'Vira-Lata (SRD)', '3 anos', '12.5 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Walle', 'GATO', 'MACHO', 'Vira-Lata (SRD)', '7 meses', '2.7 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Xena', 'CACHORRO', 'FEMEA', 'Rottweiler', '2 anos', '38.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal'),
('Yuki', 'GATO', 'FEMEA', 'Siames', '1 ano', '3.6 kg', NULL, 'Av. Maria Lacerda (Abrigo)', '500', 'Parnamirim'),
('Zack', 'CACHORRO', 'MACHO', 'Labrador', '3 anos', '29.0 kg', NULL, 'Rua das Ostras (Sede ONG)', '100', 'Natal');